"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import styles from '../app/utils.module.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
import TopHeader from '@/components/TopHeader'
import Head from 'next/head'
import Footer from '@/components/Footer'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { useState } from 'react'
import AppContext from '@/AppContext'
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [productDetails, setProductDetails] = useState(["sfsfks"]);
  return (
    <html lang="en">
      <Head>
        <title>First Post</title>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </Head>
      <body className={inter.className}>
        <TopHeader />
        <AppContext.Provider value={{productDetails, setProductDetails}}>
        <div className={styles.container}>
          <Header />
          <div className='d-flex'>
            <Sidebar />
            <div className={styles.content}>
              {children}
            </div>
          </div>
        </div>
        </AppContext.Provider>
        <Footer />
      </body>
    </html>
  )
}
